title: UrbanIntel
email: suminhan@kaist.ac.kr
description: >- # this means to ignore newlines until "baseurl:"
  Urban Intelligence for Smart City
github_username:  urbanintel

logo_img: /assets/urbanintel.svg
favicon: /assets/favicon.ico
description: description
# global_tags: jekyll theme simplex golasblog responsive html5
copyright: © UrbanIntel 2021

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"